In [1]:
FLIGHT_SALES_PATH = '/home/chk/Documents/univ/maestria/dataton/Datathon/flight_sales.csv'

In [2]:
import pandas as pd

In [4]:
dtype_options = {
    'Unnamed: 0': 'int64',
    'Flight_ID': 'str',
    'ProductType': 'str',
    'ProductName': 'str',
    'Quantity': 'float64',
    'TotalSales': 'float64',
    'Aeronave': 'str',
    'DepartureStation': 'str',
    'ArrivalStation': 'str',
    'DestinationType': 'str',
    'Origin_Type': 'str',
    'Capacity': 'float64',
    'Passengers': 'float64',
    'Bookings': 'float64'
}

parse_dates = ['STD', 'STA']

flightSales = pd.read_csv(FLIGHT_SALES_PATH, dtype=dtype_options, parse_dates=parse_dates)
flightSales.head()

,Unnamed: 0,Flight_ID,ProductType,ProductName,Quantity,TotalSales,Aeronave,DepartureStation,ArrivalStation,Destination_Type,Origin_Type,STD,STA,Capacity,Passengers,Bookings
0,0,a05290288259526edd3601160b10e1de,Botanas,Carne Seca Habanero,1.0,55.0,XA-VIQ,AW,AO,Ciudad Principal,Ciudad Principal,2023-08-28 19:20:00,2023-08-28 20:45:00,186.0,131.0,100.0
1,1,a05290288259526edd3601160b10e1de,Botanas,Cheetos,2.0,98.0,XA-VIQ,AW,AO,Ciudad Principal,Ciudad Principal,2023-08-28 19:20:00,2023-08-28 20:45:00,186.0,131.0,100.0
2,2,a05290288259526edd3601160b10e1de,Botanas,Ruffles Queso,6.0,294.0,XA-VIQ,AW,AO,Ciudad Principal,Ciudad Principal,2023-08-28 19:20:00,2023-08-28 20:45:00,186.0,131.0,100.0
3,3,a05290288259526edd3601160b10e1de,Specials,Capitan Morning,1.0,-10.0,XA-VIQ,AW,AO,Ciudad Principal,Ciudad Principal,2023-08-28 19:20:00,2023-08-28 20:45:00,186.0,131.0,100.0
4,4,a05290288259526edd3601160b10e1de,Refrescos,Coca Sin Azucar,2.0,96.0,XA-VIQ,AW,AO,Ciudad Principal,Ciudad Principal,2023-08-28 19:20:00,2023-08-28 20:45:00,186.0,131.0,100.0

In [7]:
flightSales['STD'] = pd.to_datetime(flightSales['STD'])
flightSales['STA'] = pd.to_datetime(flightSales['STA'])
flightSales.head()

,Unnamed: 0,Flight_ID,ProductType,ProductName,Quantity,TotalSales,Aeronave,DepartureStation,ArrivalStation,Destination_Type,Origin_Type,STD,STA,Capacity,Passengers,Bookings
0,0,a05290288259526edd3601160b10e1de,Botanas,Carne Seca Habanero,1.0,55.0,XA-VIQ,AW,AO,Ciudad Principal,Ciudad Principal,2023-08-28 19:20:00,2023-08-28 20:45:00,186.0,131.0,100.0
1,1,a05290288259526edd3601160b10e1de,Botanas,Cheetos,2.0,98.0,XA-VIQ,AW,AO,Ciudad Principal,Ciudad Principal,2023-08-28 19:20:00,2023-08-28 20:45:00,186.0,131.0,100.0
2,2,a05290288259526edd3601160b10e1de,Botanas,Ruffles Queso,6.0,294.0,XA-VIQ,AW,AO,Ciudad Principal,Ciudad Principal,2023-08-28 19:20:00,2023-08-28 20:45:00,186.0,131.0,100.0
3,3,a05290288259526edd3601160b10e1de,Specials,Capitan Morning,1.0,-10.0,XA-VIQ,AW,AO,Ciudad Principal,Ciudad Principal,2023-08-28 19:20:00,2023-08-28 20:45:00,186.0,131.0,100.0
4,4,a05290288259526edd3601160b10e1de,Refrescos,Coca Sin Azucar,2.0,96.0,XA-VIQ,AW,AO,Ciudad Principal,Ciudad Principal,2023-08-28 19:20:00,2023-08-28 20:45:00,186.0,131.0,100.0